version: "3.3"
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file:
      - .env
    links:
      - db:db

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: