---
- name: Deploy WordPress
  hosts: web
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose

    - name: Copy Docker Compose file
      copy:
        src: /path/to/docker-compose.yml
        dest: /home/user/docker-compose.yml

    - name: Start Docker containers
      command: docker-compose up -d